<div class="row">
  <div class="col-sm-12 carousel slide"  id="demo"  data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
      <li data-target="#demo" data-slide-to="3"></li>
      <li data-target="#demo" data-slide-to="4"></li>


    </ul>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="Imagenes/Carrusel/oferta1.png" alt="Los Angeles" width="1100" height="500">                <div class="carousel-caption">

          <p>Procesador Intel Core I7-7700K 4.2GHz BOX</p>
        </div>
      </div>
      <div class="carousel-item ">
        <img src="Imagenes/Carrusel/oferta2.png" alt="Los Angeles" width="1100" height="500">                <div class="carousel-caption">

          <p>ASUS VX248H 24" LED</p>
        </div>
      </div>
      <div class="carousel-item ">
        <img src="Imagenes/Carrusel/oferta3.png" alt="Los Angeles" width="1100" height="500">                <div class="carousel-caption">

          <p>MSI GeForce GTX 1050Ti GAMING X 4GB GDDR5</p>
        </div>
      </div>
      <div class="carousel-item ">
        <img src="Imagenes/Carrusel/oferta4.png" alt="Los Angeles" width="1100" height="500">                <div class="carousel-caption">

          <p>G.Skill Ripjaws V Red DDR4 3000 PC4-24000 16GB 2x8GB</p>
        </div>
      </div>
      <div class="carousel-item ">
        <img src="Imagenes/Carrusel/oferta5.png" alt="Los Angeles" width="1100" height="500">                <div class="carousel-caption">
          
          <p>Gigabyte GA-AB350-GAMING 3</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>

</div>
