<!-- Carrousel -->
    <div id="carouselPromociones" class="carousel slide bg-light" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <?php
        foreach ($data_carousel as $dato) {
          if($dato['ID'] == 1){
            $active = "active";
          } else {
            $active = "";
          }
          ?>
          <div class="carousel-item <?php echo $active ?>">
            <img class="carroussel_img d-block img-fluid" src="<?php echo $dato['URL']; ?>">
            <div id="OfertaCarrusel" class="d-flex flex-column text-center">
              <div class="">
                <?php echo "Antes <del>".$dato['PRICE']."€"; ?> </del>
              </div>
              <div class="">
                <?php echo "OFERTA ".$dato['DISCOUNTEDPRICE']."€"; ?>
              </div>
              <div class="">
                <?php echo "-".$dato['DISCOUNTPERCENTAGE']."% de descuento"; ?>
              </div>
            </div>


            <div class="text-center d-none d-md-block" id="NombreArtCarrusel">

                <h3> <?php echo $dato['SHORTDESCRIPTION']; ?></h3>

            </div>
          </div>
          <?php
        }
        ?>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only ">Next</span>
      </a>

    </div>
    <!-- /Carrousel -->
