


          <!-- Carrusel -->

            <div id="demo" class="row carousel slide " data-ride="carousel" style="
            margin-bottom: 50px;
            ">
            <ul class="carousel-indicators">
              <li data-target="#demo" data-slide-to="0" class="active"></li>
              <li data-target="#demo" data-slide-to="1"></li>
              <li data-target="#demo" data-slide-to="2"></li>
            </ul>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="Imagenes/Carrusel/acer-predator-x35-1.jpg" alt="Los Angeles" width="1100" height="500">
                <div class="carousel-caption">
                  <h3>Los Angeles</h3>
                  <p>We had such a great time in LA!</p>
                </div>
              </div>
              <div class="carousel-item">
                <img src="Imagenes/Carrusel/GTX-TITAN-Xp-7.jpg" alt="Chicago" width="1100" height="500">
                <div class="carousel-caption">
                  <h3>Chicago</h3>
                  <p>Thank you, Chicago!</p>
                </div>
              </div>
              <div class="carousel-item">
                <img src="Imagenes/Carrusel/gigabyte-ab350m-gaming-3-socket-am4-placa-base-1.jpeg" alt="New York" width="1100" height="500">
                <div class="carousel-caption">
                  <h3>New York</h3>
                  <p>We love the Big Apple!</p>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
              <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
              <span class="carousel-control-next-icon"></span>
            </a>
          </div>
