<?php include 'header_view.phtml' ; ?>

<?php

$cestaVacia = $_SESSION["cesta"];

if ($cestaVacia == null){

  echo "<p class=text-light>La cesta está vacía</p>";

} else { ?>

<div class="container table-responsive-sm">
  <table clas="table ">
    <thead>
      <tr>
        <th class="text-light">Imagen</th>
        <th class="text-light">Descripción</th>
        <th class="text-light">Cantidad</th>
        <th class="text-light"> Precio Unidad</th>

      </tr>
    </thead>
  </tbody>
<?php

$precio = 0;

foreach ($cesta21 as $compra) {

  ?><tr>
  <td><img class="card-img-top img_cesta" src="<?php echo $compra['URL']; ?>" alt="Card image"></td>
  <td class="text-light"><?php echo $compra["SHORTDESCRIPTION"];?></td>
  <td class="text-light"> <input type="number" class="form-control " value="1" ></td>
  <td class="text-light"><?php echo $compra["PRICE"];?>€</td>

  <td>
    <a href="index.php?controller=productos&action=borrarcesta&numero1=<?php echo $compra["ID"];?>">
      <button>Eliminar</button>
    </a>
  </td>
  </tr><?php

  $precio = $precio + $compra["PRICE"];

}

?>
<tr>

<td class="text-light"><dt>Precio final: <?php echo $precio;?> €.</dt></td>

<tr>

  </tbody>
</table>

  <?php   if(isset($_SESSION["usuario"])){ ?>

    <a href="index.php?controller=productos&action=finalizar&direccion=<?php echo $usuarioactuafinCesta[0]['ADRESS']; ?>">

      <button >Finalizar</button>
    </a>

    <a href="index.php?controller=productos&action=vaciarCarrito">

      <button >Vaciar</button>
    </a>

  <?php } else { ?>

    <a class="text-light" href="index.php">Volver</a>

  <?php } ?>

</div>

<?php } ?>


<?php include 'footer_view.phtml' ; ?>
