<?php include 'header_view.phtml' ; ?>

    <h2 class="text-white">Agregar producto</h2>

    <form action="index.php?controller=productos&action=insert_productos" id="crearProducto" method="POST">



  <label class="text-white" id="nCategoria" >Categoria:</label>
      <select name="category">
        <?php
        foreach ($datoshijas as $datohija) {
          echo "<option value={$datohija['ID']}>{$datohija['NAME']} </option>";
        }  ?>

      </select><br>



      <label class="text-white" id="nMarca" >Marca:</label>
          <select name="brand">
            <?php
            foreach ($datosmarcas as $datosmarca) {
              echo "<option value={$datosmarca['ID']}>{$datosmarca['NAME']} </option>";
            }  ?>

          </select>


      <div class="form-inline text-white">
        <label id="nPrecio">Precio: </label>
        <input type="text" class="form-control" id="price" placeholder="€" name="price" >
      </div>

      <div class="form-inline text-white">
        <label id="nStock">Stock: </label>
        <input type="text" class="form-control" id="stock" placeholder="stock" name="stock" >
      </div>

      <div class="form-inline text-white">
        <label id="nNombre">Nombre: </label>
        <input type="text" class="form-control" id="nombre" placeholder="Ej. Asus Z370-F Gaming" name="nombre" >
      </div>



      <div class="form-inline text-white">
        <label id="nDescc">Descripción corta: </label>
        <input type="text" class="form-control" id="descorta" placeholder="Ej. Asus Z370-F Gaming" name="descorta">
      </div>

      <div class="form-inline text-white">
        <label id="nDescl">Descripción larga: </label>
        <input type="text" class="form-control" id="deslarga" placeholder="Ej. Nueva placa base..." name="deslarga">
      </div>
      <br>


      <button type="submit" name="insert_productos" class="btn btn-info btn-lg" id="nEnviar" >Crear producto</button>
    </form>


<?php include 'footer_view.phtml' ; ?>
