<?php include 'header_view.phtml' ; ?>


<link rel="stylesheet" type="text/css" href="galeria.css">
<!-- Código PHP -->

<!-- Cuadraditos -->
<nav class="breadcrumb">
  <a class="breadcrumb-item text-secondary" href="#">Ordenadores</a>
  <a class="breadcrumb-item text-secondary" href="#">Portatiles</a>
  <span class="breadcrumb-item active text-dark"><?php echo $PRODUCT['SHORTDESCRIPTION'] ?></span>
</nav>
<div class="row contenido">

  <div class="col-11 col-sm-4  col-md-4" >

    <img class="img-fluid" src="<?php echo $PRODUCT['URL'] ?>" >
    <!-- Galeria -->


    <div class="row galeriaEspacio">
      <div class="column">
        <img src="Imagenes/Galeria/1.jpg"  onclick="openModal();currentSlide(1)" class="hover-shadow cursor">
      </div>
      <div class="column">
        <img src="Imagenes/Galeria/2.jpg"  onclick="openModal();currentSlide(2)" class="hover-shadow cursor">
      </div>
      <div class="column">
        <img src="Imagenes/Galeria/3.jpg" onclick="openModal();currentSlide(3)" class="hover-shadow cursor">
      </div>
      <div class="column">
        <img src="Imagenes/Galeria/4.jpg"  onclick="openModal();currentSlide(4)" class="hover-shadow cursor">
      </div>
    </div>

    <div id="myModal2" class="modal">
      <span class="close cursor" onclick="closeModal()">&times;</span>
      <div class="modal-content">

        <div class="mySlides">
          <div class="numbertext">1 / 4</div>
          <img src="Imagenes/Galeria/1.jpg" class="SlidesW100">
        </div>

        <div class="mySlides">
          <div class="numbertext">2 / 4</div>
          <img src="Imagenes/Galeria/2.jpg" class="SlidesW100">
        </div>

        <div class="mySlides">
          <div class="numbertext">3 / 4</div>
          <img src="Imagenes/Galeria/3.jpg" class="SlidesW100">
        </div>

        <div class="mySlides">
          <div class="numbertext">4 / 4</div>
          <img src="Imagenes/Galeria/4.jpg" class="SlidesW100">
        </div>

        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>

        <div class="caption-container">
          <p id="caption"></p>
        </div>


        <div class="column">
          <img class="demo cursor SlidesW100" src="Imagenes/Galeria/1.jpg" onclick="currentSlide(1)" >
        </div>
        <div class="column">
          <img class="demo cursor SlidesW100" src="Imagenes/Galeria/2.jpg" onclick="currentSlide(2)" >
        </div>
        <div class="column">
          <img class="demo cursor SlidesW100" src="Imagenes/Galeria/3.jpg"  onclick="currentSlide(3)" >
        </div>
        <div class="column">
          <img class="demo cursor SlidesW100" src="Imagenes/Galeria/4.jpg"  onclick="currentSlide(4)" >
        </div>
      </div>
    </div>
    <!-- fin galeria -->
  </div>


  <div class="col-11 col-sm-8  col-md-8 text-white collapseWhite" >

    <h4 ><?php echo $PRODUCT['SHORTDESCRIPTION'] ?> </h4>

    <a href="#demo"  data-toggle="collapse" >Información</a>
    <div id="demo" class="collapse">
      <p><?php echo $PRODUCT['LONGDESCRIPTION'] ?></p>
    </div>



    <h1 ><?php echo $PRODUCT['PRICE'] ?> €</h1>

    <small> <?php
    if ($PRODUCT['STOCK'] == 0) { ?>
      <span class="stock0"> <?php echo "No quedan productos"; ?></span>
      <?php
    } elseif ($PRODUCT['STOCK'] < 5) { ?>
      <span class="stockPoco"> <?php echo "Quedan pocos en stock"; ?></span>
    <?php } else{?>
      <span class="stockMucho"> <?php echo "Hay productos en stock"; ?></span>
    <?php } ?>
  </small><br><br>

  <a href="index.php?controller=productos&action=cesta&id=<?php echo $PRODUCT['ID'];?>&uni=<?php echo $PRODUCT['STOCK'];?>" class="btn btn-primary">Comprar</a>




</div>
</div>

<!-- FIN Cuadraditos -->

<script>
function openModal() {
  document.getElementById('myModal2').style.display = "block";
}

function closeModal() {
  document.getElementById('myModal2').style.display = "none";
}

var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>


<?php include 'footer_view.phtml' ; ?>
