<?php include 'header_view.phtml' ;
include 'carrusel_view.phtml' ;
?>


        <!-- Código PHP -->

        <!-- Cuadraditos -->
        <div class="row contenido">
          <?php

          foreach ($datos as $dato) {
            ?>
            <div class=" productos text-center card col-11 col-sm-5 col-lg-3" style= "margin: 10px;" >
              <a  href="index.php?controller=producto&action=get_producto&ID=<?php echo$dato['ID']?>" > <img class="card-img-top" src="<?php echo $dato['URL'] ?>"
              alt="Card image" style="width:100%"></a>
              <div class="card-body">
                <h4 class="card-title" ><?php echo $dato['SHORTDESCRIPTION'] ?> </h4>
                <h1 class="card-text"><?php echo $dato['PRICE'] ?> €</h1>
                <!-- <p>Stock: <?php echo $dato['STOCK'] ?> </p> -->

                <small> <?php
                if ($dato['STOCK'] == 0) { ?>
                  <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                  <?php
                } elseif ($dato['STOCK'] < 5) { ?>
                      <span style="color:orange"> <?php echo "Quedan pocos en stock"; ?></span>
                    <?php } else{?>
                        <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
                    <?php } ?>
              </small><br><br>
                <a href="#" class="btn btn-primary">Comprar</a>

              </div>
            </div>
            <?php
          }
          ?>
          <!-- FIN Cuadraditos -->
            </div>


<?php include 'footer_view.phtml' ; ?>
