<?php include 'header_view.phtml' ; ?>

<!-- Código PHP -->

<!-- Cuadraditos -->
<div class="row contenido productos" >
  <?php




  foreach ($datos as $dato) {
    ?>
    <div class="productos1 text-center card col-11 col-sm-5 col-lg-3 "  >
      <a  href="index.php?controller=productos&action=get_producto&ID=<?php echo$dato['ID']?>" > <img class="card-img-top" src="<?php echo $dato['URL'] ?>"
        alt="Card image" ></a>
        <div class="card-body">
          <h4 class="card-title" ><?php echo $dato['SHORTDESCRIPTION'] ?> </h4>
          <h1 class="card-text"><?php echo $dato['PRICE'] ?> €</h1>

          <small> <?php
          if ($dato['STOCK'] == 0) { ?>
            <span class="stock0"> <?php echo "No quedan productos"; ?></span>
            <?php
          } elseif ($dato['STOCK'] < 5) { ?>
            <span class="stockPoco" ><?php echo "Quedan pocos en stock"; ?></span>
          <?php } else{?>
            <span class="stockMucho"> <?php echo "Hay productos en stock"; ?></span>
          <?php } ?>
        </small><br><br>

        <a href="index.php?controller=productos&action=cesta&id=<?php echo $dato['ID'];?>&uni=<?php echo $dato['STOCK'];?>"  class="btn btn-primary">Comprar</a>

      </div>
    </div>
    <?php
  }
  ?>
  <!-- FIN Cuadraditos -->
</div>

<div class="row">
  <div class="col-12 col-sm-12 col-md-12 center-block" >
     <ul class="pagination pagination-lg">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul></div>
</div>

<?php include 'footer_view.phtml' ; ?>
