<?php include 'header_view.phtml' ;
include 'carrusel_view.phtml' ;

?>


<!-- Código PHP -->

<!-- Cuadraditos -->
<div class="row contenido productos">
  <?php

  foreach ($datos as $dato) {
    ?>
    <div class=" productos1 text-center card col-11 col-sm-5 col-lg-3 "  style="width:400px" >
      <a  href="index.php?controller=productos&action=get_producto&ID=<?php echo$dato['ID']?>" > <img class="card-img-top" src="<?php echo $dato['URL'] ?>"
        alt="Card image" style="width:100%"></a>
        <div class="card-body">
          <h4 class="card-title" ><?php echo $dato['SHORTDESCRIPTION'] ?> </h4>
          <h1 class="card-text"><?php echo $dato['PRICE'] ?> €</h1>


          <small> <?php
          if ($dato['STOCK'] == 0) { ?>
            <span style="color:red"> <?php echo "No quedan productos"; ?></span>
            <?php
          } elseif ($dato['STOCK'] < 5) { ?>
            <span style="color:orange"> <?php echo "Quedan pocos en stock"; ?></span>
          <?php } else{?>
            <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
          <?php } ?>
        </small><br><br>
        <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID']?>&productName=<?php echo $dato['SHORTDESCRIPTION']?>
      &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL']?>&productStock=<?php echo $dato['STOCK']?> " class="btn btn-primary">Comprar</a>

      </div>
    </div>
    <?php
  }
  ?>
  <!-- FIN Cuadraditos -->
</div>

<div class="row">
  <div class=" col-2">
                <form action="index.php?controller=productos&action=mComprar" method="post">
                <label>-Marca-</label>
                <br>
                <?php foreach ($marcas as $marca) { ?>

                  <input type="checkbox" name="marca" value="<?php echo $marca['ID']; ?>"><?php echo $marca['NAME']; ?><br>

                <?php } ?>
                <input type="submit" value="Buscar"><br><hr>
                <label>-Precios-</label>
                <br>
              </form>
              <form action="index.php?controller=productos&action=dComprar" method="post">
                <input type="number" class="form-control pequeno" value="0" name="precioMinimo">
                <label>hasta</label>
                <input type="number" class="form-control pequeno" value="100" name="precioMaximo">
                <br>
                <input type="submit" value="Buscar"><br><hr>
              </form>
              </div>
</div>
<?php include'controllers/paginacion_controller.php'; ?>

<?php include 'footer_view.phtml' ; ?>
