<?php include 'header_view.phtml' ; ?>



<!--  Formulario-->
<div class="container">

<br>
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#home">Login</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#menu1">Registratse</a>
  </li>

</ul>

<!-- LOGIN -->
<div class="tab-content">
  <div id="home" class="container tab-pane active"><br>
     <form action="index.php?controller=usuarios&action=login" method="post">
              <div class="form-group text-white">
                <label for="email">Nombre:</label>
                <input type="text" class="form-control" id="email" placeholder="Enter email" name="name">
              </div>
              <div class="form-group text-white">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd">
              </div>

              <button type="submit" class="btn btn-primary">Submit</button>
            </form>

  </div>

  <!-- Registratse -->
  <div id="menu1" class="container tab-pane fade"><br>

              <form action="index.php?controller=usuarios&action=insert" method="post">

              <div class="form-group text-white">
                <label for="username">Nombre de usuario:</label>
                <input type="text" class="form-control" id="username" placeholder="Nombre de usuario" name="username">
              </div>
              <div class="form-group text-white">
                <label for="name">Nombre y apellidos:</label>
                <input type="text" class="form-control" id="name" placeholder="Nombre completo" name="name">
              </div>
              <div class="form-group text-white">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
              </div>
              <div class="form-group text-white">
                <label for="password">Password:</label>
                <input type="password" class="form-control" id="password" placeholder="Password" name="password">
              </div>
              <!-- <div class="form-group">
              <label for="pwd">Repeat password:</label>
              <input type="password" class="form-control" id="pwd" placeholder="Repeat password" name="pswd2">
            </div> -->
            <div class="form-group text-white">
              <label for="direccion">Dirección:</label>
              <input type="text" class="form-control" id="direccion" placeholder="Dirección" name="direccion">
            </div>
            <div class="form-group text-white">
              <label for="cp">CP:</label>
              <input type="text" class="form-control" id="cp" placeholder="Codigo Postal" name="cp">
            </div>

            <button type="submit" name="insert" value="Guardar "class="btn btn-primary">Submit</button>
          </form>

  </div>
  
</div>
</div>

<?php include 'footer_view.phtml' ; ?>
