  <!--  inicio hedarer view-->

  <html lang="es">
  <head>
    <title>GMS Informática</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="estilos.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <script src="usuarios_add.js"></script>

    <!--   Hacer que el botón de perfil y menu sea desplegable con hover  -->

    <script>
    $('body').on('mouseenter mouseleave','.dropdown-hover',function(e){
      var _d=$(e.target).closest('.dropdown-hover');_d.addClass('show');
      setTimeout(function(){
        _d[_d.is(':hover')?'addClass':'removeClass']('show');
      },300);
    });
    </script>



  </head>

  <body class="bg-dark" onload="funcion1()">

    <div class="container-fluid ">

      <header>

        <!-- Menu superior -->
        <div class="row align-items-start bg-light text-dark">

          <div class=" col-12 col-sm-12 col-md-3" >
            <!-- Brand/logo -->
            <a class="navbar-brand img-fluid" href="index.php" id="logoGMS" >
              <img src="Imagenes/Web/logo.png" alt="logo" >
            </a>
          </div>

          <div class=" col-12 col-sm-12 col-md-4" >
            <!-- Buscador -->
            <form class="form-inline" action="index.php?controller=productos&action=search" method="POST">
              <input class="form-control mr-sm-2" type="search" name="buscador" placeholder="Buscar..." aria-label="Buscar">
              <button class="btn btn-info " type="submit">Search</button>
            </form>
          </div>

          <div class=" col-8 col-sm-8 col-md-3" >
            <!-- Login -->
            <?php if (isset($_SESSION['name'])) {

              //Si el usuario es admin, muestra lo siguiente
              if ($_SESSION['name'] == "admin") {

                ?>

                <!-- Menu de coniguración -->
                <div class="dropdown" >
                  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                    Configuración
                  </button>
                  <div class="dropdown-menu ">
                    <a class="dropdown-item" href="index.php?controller=productos&action=add_productos">Añadir productos</a>
                    <a class="dropdown-item" href="index.php?controller=categorias&action=add_categorias">Añadir categorias</a>
                    <a class="dropdown-item disabled" href="#">Añadir promociones</a>
                    <a class="dropdown-item " href="index.php?controller=usuarios&action=logout">Logout</a>
                  </div>
                </div>



                <?php


              }else {
                //Si esta registrado pero no es el usuario admin

                ?>

                <div class="dropdown dropdown-hover" >
                  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                    Perfil
                  </button>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Hola <?php echo $_SESSION['name']; ?></a>


                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item disabled" href="#">Editar perfil</a>
                    <a class="dropdown-item" href="#">Histórico de compras</a>
                    <a class="dropdown-item" href="index.php?controller=usuarios&action=logout">Logout</a>
                  </div>
                </div>

                <?php
              }

            }  else {
              ?>

              <!-- <button type="button" class="btn btn-info btn-lg" href="index.php?controller=usuarios&action=add" >Entra o regístrate</button> -->

              <a type="button" class="btn btn-info btn-lg" href="index.php?controller=usuarios&action=add" >Entra o regístrate</a>
              <?php
            }?>

          </div>

          <div class="col-4 col-sm-4 col-md-2" >
            <!-- inicio carrito -->


              <!-- Carrito -->
              <!-- Brand/logo -->
              <a class="navbar-brand" href="index.php?controller=productos&action=cestaok" id="logoCarrito">
                <img src="Imagenes/Web/carrito.png" alt="logo" onmouseover="mostrarCarr()" onmouseout="ocultarCarr()">
                <span class="badge badge-light">1</span>
              </a>

              <div class="table-responsive-sm invisible " id="carroFloat">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Imagen</th>
                      <th>Cantidad</th>
                      <th>Precio Unidad</th>
                      <th>Descripción</th>

                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><img class="img-fluid" src="https://img.pccomponentes.com/articles/11/112147/intel-i5-6600k-3-5ghz.jpg" ></td>
                      <td>1</td>
                      <td>156€</td>
                      <td>Procesador Intel Core i5-7400 3.0GHz BOX</td>

                    </tr>
                  </tbody>
                </table>
              </div>




            <!-- fin carrito -->

          </div>
        </div>
        <!-- Menu superior fin -->

        <div class="row">
          <!-- Menu categorias -->
          <div class="col-md-12" >
            <nav class=" row navbar navbar-expand-md bg-dark navbar-dark">
              <a class="navbar-brand" href="#">Categorias</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                  <!-- Dropdown -->
                  <li class="nav-item dropdown dropdown-hover">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                      Componentes
                    </a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="index.php?controller=productos&action=verProcesadores">Procesadores</a>
                      <a class="dropdown-item" href="index.php?controller=productos&action=verGraficas">Gráficas</a>
                      <a class="dropdown-item" href="index.php?controller=productos&action=verRam">Memorias Ram</a>
                      <a class="dropdown-item" href="index.php?controller=productos&action=verPBase">Placas Base</a>

                    </div>

                    <!-- Dropdown -->
                    <li class="nav-item dropdown dropdown-hover">
                      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Perifericos
                      </a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="index.php?controller=productos&action=verMonitores">Monitores</a>
                        <a class="dropdown-item" href="index.php?controller=productos&action=verTeclados">Teclados</a>
                        <a class="dropdown-item" href="index.php?controller=productos&action=verRatones">Ratones</a>
                      </div>

                      <!-- Dropdown -->
                      <li class="nav-item dropdown dropdown-hover">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                          Ordenadores
                        </a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="index.php?controller=productos&action=verPortatiles">Portatiles</a>
                          <a class="dropdown-item" href="index.php?controller=productos&action=verPCSobremesa">PC Sobremesa</a>

                        </div>

                      </ul>
                    </div>
                  </nav>
                </div>
              </div>
              <!--Fin Menu categorias  -->

            </header>

            <script>

            function mostrarCarr() {
              document.getElementById("carroFloat").classList.remove("invisible");
            }

            function ocultarCarr() {
              document.getElementById("carroFloat").classList.add("invisible");
            }
            </script>

            <!-- fin header_view -->


    <div class="contenido">

<!--  Formulario-->
<div class="container">


<br>
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#home">Login</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#menu1">Registratse</a>
  </li>

</ul>

<!-- LOGIN -->
<div class="tab-content">
  <div id="home" class="container tab-pane active"><br>
     <form action="index.php?controller=usuarios&action=login" method="post">
              <div class="form-group text-white">
                <label for="email">Nombre:</label>
                <input type="text" class="form-control" id="nombre" placeholder="Introducir Nombre" name="name">
              </div>
              <div class="form-group text-white">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" placeholder="Introducir contraseña" name="pswd">
              </div>

              <button type="submit" class="btn btn-primary">Submit</button>
            </form>

  </div>

  <!-- Registratse -->
  <div id="menu1" class="container tab-pane fade"><br>

              <form action="index.php?controller=usuarios&action=insert" method="post">


              <div class="form-group text-white">
                <label for="username">Nombre de usuario:</label>
                <input type="text" class="form-control" id="username" placeholder="Nombre de usuario" name="username"  onblur="username1()">
                  <label id="comprobacionUsername"></label>
              </div>

              <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeUsuario">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
              <strong>  Error </strong> en el campo Usuario
              </div>

              <div class="form-group text-white">
                <label for="name">Nombre y apellidos:</label>
                <input type="text" class="form-control" id="name" placeholder="Nombre completo" name="name" onblur="name1()">
                <label id="comprobacionName"></label>
              </div>

              <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeNombre">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
              <strong>  Error </strong> en el campo de Nombre y Apellidos
              </div>

              <div class="form-group text-white">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" placeholder="Introducir email" name="email" onblur="emaifinCesta()">
                <label id="comprobacionEmail"></label>
              </div>

              <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeEmail">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
              <strong>  Error </strong> en el campo de Email
              </div>

              <div class="form-group text-white">
                <label for="password">Contraseña:</label>
                <input type="password" class="form-control" id="password" placeholder="Contraseña" name="password" onblur="password1()">
                  <label id="comprobacionPassword"></label>

                  <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeContrasena1">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                  <strong>  Error </strong> en el campo Contraseña
                  </div>
              </div>
              <div class="form-group text-white">
              <label for="pwd">Repetir contraseña:</label>
              <input type="password" class="form-control" id="password2" placeholder="Repite la contraseña" name="password2" onblur="passwordrepeat()">
              <label id="comprobacionPasswordRepeticion"></label>
            </div>

            <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeContrasena">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>  Error </strong> en el campo Contraseña, no son iguales,
            </div>

            <div class="form-group text-white">
              <label for="direccion">Dirección:</label>
              <input type="text" class="form-control" id="direccion" placeholder="Dirección" name="direccion" onblur="direccion1()">
                <label id="comprobacionDireccion"></label>
            </div>

            <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeDireccion">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>  Error </strong> en el campo Dirección
            </div>

            <div class="form-group text-white">
              <label for="cp">CP:</label>
              <input type="text" class="form-control" id="cp" placeholder="Codigo Postal" name="cp" onblur="cp1()">
              <label id="comprobacionCp"></label>
            </div>

            <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeCp">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>  Error </strong> en el campo de Código Postal
            </div>

            <div class="form-group text-white">
              <label for="captcha">Captcha:</label><label id="ramdom1"></label><label> + </label><label id="ramdom2"></label>
              <input type="text" class="form-control" id="captcha" placeholder="Captcha" name="captcha" onblur="captcha1()">
              <label id="comprobacionCaptcha"></label>
            </div>

            <div class="alert alert-danger alert-dismissable fade show invisible" id="alertaDeCaptcha">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>  Error </strong> en el campo de captcha
            </div>

            <button type="submit" name="insert" value="Guardar "class="btn btn-primary" id="finaliza" disabled >Submit</button>
          </form>

  </div>

</div>
</div>

<?php include 'footer_view.phtml' ; ?>
