<!--  inicio hedarer view-->
<!DOCTYPE html>
<html lang="es">
<head>
  <title>GMS Informática</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <script src="usuarios_add.js"></script>
<link rel="stylesheet" type="text/css" href="estilos.css">
</head>

<body class="bg-dark" onload="funcion1()">

  <body class="bg-dark" >

    <div class="container-fluid ">

      <header>

        <!-- Menu superior -->
        <div class=" row align-items-start bg-light text-dark">
          <div class="col-12 col-sm-12 col-md-12 row">

            <!-- Brand/logo -->
            <a class="navbar-brand" href="http://localhost/ejercicios1/trabajo%20trimesral/" style="margin-left:25px;">
              <img src="Imagenes/Web/logo.png" alt="logo" style="width:200px;">
            </a>





            <form class="form-inline" action="/action_page.php" style="margin-right:10px;">
              <input class="form-control" type="text" placeholder="Buscar...">
              <button class="btn btn-info" type="submit">Buscar</button>
            </form>




            <?php if (isset($_SESSION['name'])) {

              //Si el usuario es admin, muestra lo siguiente
              if ($_SESSION['name'] == "admin") {

                ?>

                <!-- Menu de coniguración -->
                <div class="dropdown" style="  margin-top: 8px; margin-right:10px; ">
                  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                    Configuración
                  </button>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Añadir productos</a>
                    <a class="dropdown-item" href="index.php?controller=categorias&action=categoriasPadreView">Añadir categorias</a>
                    <a class="dropdown-item" href="#">Añadir promociones</a>
                  </div>
                </div>

                <a type="button" class="btn btn-info" href="index.php?controller=usuarios&action=logout">Logout </a>

                <?php


              }else {
                //Si esta registrado pero no es el usuario admin

                ?>

                <div class="dropdown" style="
                margin-right: 10px;
                margin-top: 8px;
                ">
                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                  Perfil
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Hola <?php echo $_SESSION['name']; ?></a>


                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item disabled" href="#">Editar perfil</a>
                  <a class="dropdown-item" href="#">Histórico de compras</a>
                </div>
              </div>
              <br>

              <a type="button" class="btn btn-info btn-lg" href="index.php?controller=usuarios&action=logout">Logout </a>
              <?php
            }

          }  else {
            ?> <a type="button" class="btn btn-info btn-lg" href="index.php?controller=usuarios&action=add">Entra o regístrate</a>
            <?php
          }?>

  <!-- inicio carrito -->

  <?php if (isset($_SESSION['name'])) {

    //Si el usuario es admin, muestra lo siguiente
    if ($_SESSION['name'] == "admin") {

      ?>



      <?php


    }else {
      //Si esta registrado pero no es el usuario admin

      ?>
      <!-- Brand/logo -->
      <a class="navbar-brand" href="#">
        <img src="Imagenes/Web/carrito.png" alt="logo" style="width:50px;">
      </a>
      <span class="badge badge-light">4</span>

    <?php
  }

  }  else {
  ?> <!-- Brand/logo -->
  <a class="navbar-brand" href="#">
    <img src="Imagenes/Web/carrito.png" alt="logo" style="width:50px;">
  </a>
  <span class="badge badge-light">4</span>
  <?php
  }?>
  <!-- fin carrito -->


        </div>
      </div>




      <!-- Menu categorias -->

      <nav class=" row navbar navbar-expand-md bg-dark navbar-dark">
        <a class="navbar-brand" href="#">Categorias</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <!-- Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Componentes
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="index.php?controller=productos&action=verProcesadores">Procesadores</a>
                <a class="dropdown-item" href="index.php?controller=productos&action=verGraficas">Gráficas</a>
                <a class="dropdown-item" href="index.php?controller=productos&action=verRam">Memorias Ram</a>
                <a class="dropdown-item" href="index.php?controller=productos&action=verPBase">Placas Base</a>

              </div>

              <!-- Dropdown -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  Perifericos
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="index.php?controller=productos&action=view">Monitores</a>
                  <a class="dropdown-item" href="index.php?controller=productos&action=verTeclados">Teclados</a>
                  <a class="dropdown-item" href="index.php?controller=productos&action=verRatones">Ratones</a>
                </div>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Ordenadores
                  </a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="index.php?controller=productos&action=verPortatiles">Portatiles</a>
                    <a class="dropdown-item" href="index.php?controller=productos&action=verPCSobremesa">PC Sobremesa</a>

                  </div>

                </ul>
              </div>
            </nav><!--Fin Menu categorias  ok-->



          </header><!-- header ok-->
<!-- fin header_view -->

    <div class="contenido">

<!--  Formulario-->
<div class="container">

<br>
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#home">Login</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#menu1">Registratse</a>
  </li>

</ul>

<!-- LOGIN -->
<div class="tab-content">
  <div id="home" class="container tab-pane active"><br>
     <form action="index.php?controller=usuarios&action=login" method="post">
              <div class="form-group text-white">
                <label for="email">Nombre:</label>
                <input type="text" class="form-control" id="nombre" placeholder="Introducir Nombre" name="name">
              </div>
              <div class="form-group text-white">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" placeholder="Introducir contraseña" name="pswd">
              </div>

              <button type="submit" class="btn btn-primary">Submit</button>
            </form>

  </div>

  <!-- Registratse -->
  <div id="menu1" class="container tab-pane fade"><br>

              <form action="index.php?controller=usuarios&action=insert" method="post">


              <div class="form-group text-white">
                <label for="username">Nombre de usuario:</label>
                <input type="text" class="form-control" id="username" placeholder="Nombre de usuario" name="username"  onblur="username1()">
                  <label id="comprobacionUsername"></label>
              </div>
              <div class="form-group text-white">
                <label for="name">Nombre y apellidos:</label>
                <input type="text" class="form-control" id="name" placeholder="Nombre completo" name="name" onblur="name1()">
                <label id="comprobacionName"></label>
              </div>
              <div class="form-group text-white">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" placeholder="Introducir email" name="email" onblur="email1()">
                <label id="comprobacionEmail"></label>
              </div>
              <div class="form-group text-white">
                <label for="password">Contraseña:</label>
                <input type="password" class="form-control" id="password" placeholder="Contraseña" name="password" onblur="password1()">
                  <label id="comprobacionPassword"></label>
              </div>
              <div class="form-group text-white">
              <label for="pwd">Repetir contraseña:</label>
              <input type="password" class="form-control" id="password2" placeholder="Repite la contraseña" name="password2" onblur="passwordrepeat()">
              <label id="comprobacionPasswordRepeticion"></label>
            </div>
            <div class="form-group text-white">
              <label for="direccion">Dirección:</label>
              <input type="text" class="form-control" id="direccion" placeholder="Dirección" name="direccion" onblur="direccion1()">
                <label id="comprobacionDireccion"></label>
            </div>
            <div class="form-group text-white">
              <label for="cp">CP:</label>
              <input type="text" class="form-control" id="cp" placeholder="Codigo Postal" name="cp" onblur="cp1()">
              <label id="comprobacionCp"></label>
            </div>
            <div class="form-group text-white">
              <label for="captcha">Captcha:</label><label id="ramdom1"></label><label> + </label><label id="ramdom2"></label>
              <input type="text" class="form-control" id="captcha" placeholder="Captcha" name="captcha" onblur="captcha1()">
              <label id="comprobacionCaptcha"></label>
            </div>

            <button type="submit" name="insert" value="Guardar "class="btn btn-primary" id="finaliza" disabled >Submit</button>
          </form>

  </div>

</div>
</div>

<?php include 'footer_view.phtml' ; ?>
